### ISSUE TITLE
can not download data and checkpoint

### ISSUE THREAD

**Issue by zlw21gxy** [felipecode/coiltraine#14]
![image](https://user-images.githubusercontent.com/46110602/56890416-f2fb0600-6aab-11e9-8017-e1501147734f.png)

**Comment by zlw21gxy** [comment]
I fixed it by modify download_tools.py
`import requests
import sys
from requests.packages.urllib3.util.retry import Retry

def download_file_from_google_drive(id, destination):
    URL = "https://docs.google.com/uc?export=download"
    session = requests.Session()
    response = session.get(URL, params={'id': id}, stream=True)
    token = get_confirm_token(response)

    if token:
        params = {'id': id, 'confirm': token}
        retry = Retry(connect=20, backoff_factor=0.1)
        response = session.get(URL, params=params, stream=True)

    save_response_content(response, destination)
`

**Comment by felipecode** [comment]
Were you able to download everything ?

**Comment by zlw21gxy** [comment]
yes, I can do it now, thanks for your great work
